export const HOLIDAY_DATA = [
  { id:"H1", name:"New Year's Day", date:"2025-01-01", day:"Wednesday", type:"National", location:"All" },
  { id:"H2", name:"Makar Sankranti", date:"2025-01-14", day:"Tuesday", type:"Regional", location:"Bangalore,Mumbai" },
  { id:"H3", name:"Republic Day", date:"2025-01-26", day:"Sunday", type:"National", location:"All" },
  { id:"H4", name:"Maha Shivratri", date:"2025-02-26", day:"Wednesday", type:"National", location:"All" },
  { id:"H5", name:"Holi", date:"2025-03-14", day:"Friday", type:"National", location:"All" },
  { id:"H6", name:"Good Friday", date:"2025-04-18", day:"Friday", type:"National", location:"All" },
  { id:"H7", name:"Dr. Ambedkar Jayanti", date:"2025-04-14", day:"Monday", type:"National", location:"All" },
  { id:"H8", name:"Maharashtra Day", date:"2025-05-01", day:"Thursday", type:"Regional", location:"Mumbai,Pune" },
  { id:"H9", name:"Eid ul-Fitr", date:"2025-03-31", day:"Monday", type:"National", location:"All" },
  { id:"H10", name:"Ram Navami", date:"2025-04-06", day:"Sunday", type:"National", location:"All" },
  { id:"H11", name:"Buddha Purnima", date:"2025-05-12", day:"Monday", type:"National", location:"All" },
  { id:"H12", name:"Eid ul-Adha", date:"2025-06-07", day:"Saturday", type:"National", location:"All" },
  { id:"H13", name:"Muharram", date:"2025-07-06", day:"Sunday", type:"National", location:"All" },
  { id:"H14", name:"Independence Day", date:"2025-08-15", day:"Friday", type:"National", location:"All" },
  { id:"H15", name:"Janmashtami", date:"2025-08-16", day:"Saturday", type:"National", location:"All" },
  { id:"H16", name:"Ganesh Chaturthi", date:"2025-08-27", day:"Wednesday", type:"Regional", location:"Mumbai,Pune,Bangalore" },
  { id:"H17", name:"Gandhi Jayanti", date:"2025-10-02", day:"Thursday", type:"National", location:"All" },
  { id:"H18", name:"Dussehra", date:"2025-10-02", day:"Thursday", type:"National", location:"All" },
  { id:"H19", name:"Diwali", date:"2025-10-20", day:"Monday", type:"National", location:"All" },
  { id:"H20", name:"Diwali (Padwa)", date:"2025-10-21", day:"Tuesday", type:"Regional", location:"Mumbai,Pune" },
  { id:"H21", name:"Guru Nanak Jayanti", date:"2025-11-05", day:"Wednesday", type:"National", location:"All" },
  { id:"H22", name:"Christmas Day", date:"2025-12-25", day:"Thursday", type:"National", location:"All" },
];
